#pragma once
#define PER_FRAME_CBUFFER_SLOT 0u
#define CAMERA_CBUFFER_SLOT 1u
#define TRANSFORM_CBUFFER_SLOT 2u
#define LIGHT_CBUFFER_SLOT 3u
#define MATERIAL_CBUFFER_SLOT 4u
#define SHADOW_CBUFFER_SLOT 5u
